class Experiment:
    def __init__(self, MODELDIR=None):
        self.MODELDIR = MODELDIR
        self.HIDDEN = 64
        self.TEST = False
        self.LOAD = False
        self.BEST = False
        self.NPOP = 5
        self.device = 'cpu'  # 'cpu' or 'cuda'
        self.ENT_DIM = 1014
        self.ENT_DIM_GLOBAL = 3024
        self.EPS_CUR = 1
        self.EPS_MIN = 0.
        self.EPS_STEP = 0.99999
        self.EXPLORE_MODE = 'eps'
        self.GAMMA = 0.99
        self.BATCH_SIZE = 2**6
        self.TARGET_PERIOD = 2**11
        self.TARGET_PERIOD_LM = 2**11
        self.BUFFER_SIZE = 2**18
        self.MIN_BUFFER = 2**13
        self.LR = 0.0005
        self.NOISE = True
        self.N_QUANT = 10
        self.N_QUANT_LM = 1
        self.REPLAY_PRIO = True
        self.REPLAY_NSTEP = 5
        self.PUNISHMENT = 1
        self.LM_FUNCTION = 'sum'  # 'sum', 'min', 'max'
        self.REPLAY_LM = True
        self.REPLAY_PRIO_LM = False * self.REPLAY_LM
        self.BATCH_SIZE_LM = 2 ** 5
        self.BUFFER_SIZE_LM = 4000 if not self.REPLAY_LM else 2 ** 17
        self.REPLAY_NSTEP_LM = 1
        self.QMIX = True
        self.COMMON = False
        self.COMMON_FUN = 'sum'
        self.VANILLA_QMIX = False  # if True, implies self.REPLAY_LM = True
        self.HORIZON = 1000
        self.NORM_INPUT = True
        self.EVAL_FREQ = 10
        self.EVAL_EPISODES = 1
